### PR TITLE
Fix.query watch

### PR DESCRIPTION
**Pull request by nfaugout**
We use Query.Watch to measure the time taken by the SQL layer.

NB : this PR should be later replaced by a stronger way to measure time taken in general, using tools from EF

### CODE REVIEW

**Comment by Poltuu** [comment]
I thought we discussed we would get ride of this ?

**Comment by rducom** [comment]
+1 We should externalize query timing.
Maybe we also should provide a simple sample App (using Miniprofiler) inside the repo

**Comment by nfaugout** [comment]
Yes we would get rid of this when somebody comes with an alternative.

In the meanwhile, I need this to work in Lucca.Auth, so I fixed it in the current implementation.

**Comment by rducom** [comment]
If we give a sample using miniprofiler, such query timming will never be in production mode, but only in dev mode for debuging / perf-analysis purposes.

**Pull request closed without merging**
