### PR TITLE
Concurrency issue on serializer resolution

### PR DESCRIPTION
**Pull request by rducom**
```
System.InvalidOperationException: Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
   at System.Collections.Generic.Dictionary<TKey,TValue>.FindEntry(TKey key)
   at Rdd.Web.Serialization.Providers.SerializerProvider.ResolveSerializer(Object entity)
   at Rdd.Web.Serialization.RddJsonResult<T>.WriteResult(IServiceProvider services, TextWriter writer, DateTime generatedAt)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultAsync(IActionResult result)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResultFilterAsync[TFilter,TFilterAsync]()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResultExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeResultFilters()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
```

Occurs on last RC

### CODE REVIEW

**Comment by rducom** [comment]
I'm deploying this fix in production before merging this PR

**Comment by Poltuu** [comment]
you do you boo

**Comment by Poltuu** [comment]
mmm, we should have added a test on this one

**Comment by rducom** [comment]
concurrent dictionary collision can't be easily reproduced

**Pull request merged**
